"""add_hiring_tables

Revision ID: 2d1a9cd17920
Revises: 8d413be024e0
Create Date: 2026-05-28 21:09:57.101718

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2d1a9cd17920"
down_revision: str | Sequence[str] | None = "8d413be024e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_openings",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("requirements", sa.Text(), nullable=True),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("position_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("slots_needed", sa.Integer(), nullable=False),
        sa.Column("slots_filled", sa.Integer(), nullable=False),
        sa.Column("min_salary", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("max_salary", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("posted_date", sa.Date(), nullable=True),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("closed_date", sa.Date(), nullable=True),
        sa.Column("requested_by_user_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_openings_deleted_at"), "job_openings", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_job_openings_department_id"), "job_openings", ["department_id"], unique=False
    )
    op.create_index(op.f("ix_job_openings_status"), "job_openings", ["status"], unique=False)
    op.create_index(
        "ix_job_openings_status_dept", "job_openings", ["status", "department_id"], unique=False
    )
    op.create_table(
        "job_applications",
        sa.Column("job_opening_id", sa.UUID(), nullable=False),
        sa.Column("candidate_name", sa.String(length=200), nullable=False),
        sa.Column("candidate_email", sa.String(length=255), nullable=False),
        sa.Column("candidate_phone", sa.String(length=20), nullable=True),
        sa.Column("resume_url", sa.String(length=500), nullable=True),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("referrer_user_id", sa.UUID(), nullable=True),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("stage_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("rejection_stage", sa.String(length=30), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("offered_salary", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("offered_start_date", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_opening_id"], ["job_openings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["referrer_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_applications_opening_stage",
        "job_applications",
        ["job_opening_id", "stage"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_applications_candidate_email"),
        "job_applications",
        ["candidate_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_applications_job_opening_id"),
        "job_applications",
        ["job_opening_id"],
        unique=False,
    )
    op.create_index(op.f("ix_job_applications_stage"), "job_applications", ["stage"], unique=False)
    op.create_table(
        "interviews",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("interview_type", sa.String(length=30), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("location_or_link", sa.String(length=500), nullable=True),
        sa.Column("interviewer_user_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result", sa.String(length=20), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["application_id"], ["job_applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interviews_application_id"), "interviews", ["application_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_interviews_application_id"), table_name="interviews")
    op.drop_table("interviews")
    op.drop_index(op.f("ix_job_applications_stage"), table_name="job_applications")
    op.drop_index(op.f("ix_job_applications_job_opening_id"), table_name="job_applications")
    op.drop_index(op.f("ix_job_applications_candidate_email"), table_name="job_applications")
    op.drop_index("ix_applications_opening_stage", table_name="job_applications")
    op.drop_table("job_applications")
    op.drop_index("ix_job_openings_status_dept", table_name="job_openings")
    op.drop_index(op.f("ix_job_openings_status"), table_name="job_openings")
    op.drop_index(op.f("ix_job_openings_department_id"), table_name="job_openings")
    op.drop_index(op.f("ix_job_openings_deleted_at"), table_name="job_openings")
    op.drop_table("job_openings")
    # ### end Alembic commands ###
