"""add_onboarding_tables

Revision ID: 31463f8d1246
Revises: 2d1a9cd17920
Create Date: 2026-05-28 21:22:09.238034

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31463f8d1246"
down_revision: str | Sequence[str] | None = "2d1a9cd17920"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding_templates",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("target_department_id", sa.UUID(), nullable=True),
        sa.Column("target_position_level", sa.Integer(), nullable=True),
        sa.Column("estimated_duration_days", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["target_department_id"],
            ["departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_onboarding_templates_deleted_at"),
        "onboarding_templates",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_onboarding_templates_is_active"),
        "onboarding_templates",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_onboarding_templates_target_department_id"),
        "onboarding_templates",
        ["target_department_id"],
        unique=False,
    )
    op.create_index(
        "ix_templates_dept_level_active",
        "onboarding_templates",
        ["target_department_id", "target_position_level", "is_active"],
        unique=False,
    )
    op.create_table(
        "onboarding_tasks",
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("default_due_offset_days", sa.Integer(), nullable=False),
        sa.Column("assigned_role", sa.String(length=30), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("reference_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["template_id"], ["onboarding_templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_onboarding_tasks_category"), "onboarding_tasks", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_onboarding_tasks_template_id"), "onboarding_tasks", ["template_id"], unique=False
    )
    op.create_index(
        "ix_tasks_template_order", "onboarding_tasks", ["template_id", "order_index"], unique=False
    )
    op.create_table(
        "onboarding_assignments",
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.Date(), nullable=False),
        sa.Column("target_completion_date", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_by_user_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["onboarding_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "template_id", name="uq_assignment_employee_template"),
    )
    op.create_index("ix_assignments_status", "onboarding_assignments", ["status"], unique=False)
    op.create_index(
        op.f("ix_onboarding_assignments_employee_id"),
        "onboarding_assignments",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_onboarding_assignments_status"), "onboarding_assignments", ["status"], unique=False
    )
    op.create_table(
        "task_completions",
        sa.Column("assignment_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("blocker_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignment_id"], ["onboarding_assignments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["completed_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["onboarding_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assignment_id", "task_id", name="uq_completion_assignment_task"),
    )
    op.create_index(
        op.f("ix_task_completions_assignment_id"),
        "task_completions",
        ["assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_completions_status"), "task_completions", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_completions_status"), table_name="task_completions")
    op.drop_index(op.f("ix_task_completions_assignment_id"), table_name="task_completions")
    op.drop_table("task_completions")
    op.drop_index(op.f("ix_onboarding_assignments_status"), table_name="onboarding_assignments")
    op.drop_index(
        op.f("ix_onboarding_assignments_employee_id"), table_name="onboarding_assignments"
    )
    op.drop_index("ix_assignments_status", table_name="onboarding_assignments")
    op.drop_table("onboarding_assignments")
    op.drop_index("ix_tasks_template_order", table_name="onboarding_tasks")
    op.drop_index(op.f("ix_onboarding_tasks_template_id"), table_name="onboarding_tasks")
    op.drop_index(op.f("ix_onboarding_tasks_category"), table_name="onboarding_tasks")
    op.drop_table("onboarding_tasks")
    op.drop_index("ix_templates_dept_level_active", table_name="onboarding_templates")
    op.drop_index(
        op.f("ix_onboarding_templates_target_department_id"), table_name="onboarding_templates"
    )
    op.drop_index(op.f("ix_onboarding_templates_is_active"), table_name="onboarding_templates")
    op.drop_index(op.f("ix_onboarding_templates_deleted_at"), table_name="onboarding_templates")
    op.drop_table("onboarding_templates")
    # ### end Alembic commands ###
