"""add_employee_separations

Revision ID: 475b24979216
Revises: 31463f8d1246
Create Date: 2026-05-28 21:50:16.489875

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "475b24979216"
down_revision: str | Sequence[str] | None = "31463f8d1246"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_separations",
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("separation_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("notice_period_days", sa.Integer(), nullable=False),
        sa.Column("severance_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("assets_to_return", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("related_warning_letter_id", sa.UUID(), nullable=True),
        sa.Column("exit_interview_notes", sa.Text(), nullable=True),
        sa.Column("exit_interview_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("initiated_by_user_id", sa.UUID(), nullable=False),
        sa.Column("approval_l1_user_id", sa.UUID(), nullable=True),
        sa.Column("approval_l1_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_l1_notes", sa.Text(), nullable=True),
        sa.Column("approval_l2_user_id", sa.UUID(), nullable=True),
        sa.Column("approval_l2_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_l2_notes", sa.Text(), nullable=True),
        sa.Column("rejected_by_user_id", sa.UUID(), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("executed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approval_l1_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["approval_l2_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["executed_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["initiated_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rejected_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["related_warning_letter_id"],
            ["warning_letters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_employee_separations_effective_date"),
        "employee_separations",
        ["effective_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_separations_employee_id"),
        "employee_separations",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_separations_separation_type"),
        "employee_separations",
        ["separation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_separations_status"), "employee_separations", ["status"], unique=False
    )
    op.create_index(
        "ix_separation_employee_status",
        "employee_separations",
        ["employee_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_separation_status_type",
        "employee_separations",
        ["status", "separation_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_separation_status_type", table_name="employee_separations")
    op.drop_index("ix_separation_employee_status", table_name="employee_separations")
    op.drop_index(op.f("ix_employee_separations_status"), table_name="employee_separations")
    op.drop_index(
        op.f("ix_employee_separations_separation_type"), table_name="employee_separations"
    )
    op.drop_index(op.f("ix_employee_separations_employee_id"), table_name="employee_separations")
    op.drop_index(op.f("ix_employee_separations_effective_date"), table_name="employee_separations")
    op.drop_table("employee_separations")
    # ### end Alembic commands ###
