"""add_leave_balances_and_request_audit_fields

Revision ID: c4869330d466
Revises: 475b24979216
Create Date: 2026-05-29 08:15:18.950974

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c4869330d466"
down_revision: str | Sequence[str] | None = "475b24979216"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leave_balances",
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("leave_type_id", sa.UUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("allocated_days", sa.Integer(), nullable=False),
        sa.Column("used_days", sa.Integer(), nullable=False),
        sa.Column("carried_over_days", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["leave_type_id"],
            ["leave_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "employee_id", "leave_type_id", "year", name="uq_balance_employee_type_year"
        ),
    )
    op.create_index(
        "ix_balance_employee_year", "leave_balances", ["employee_id", "year"], unique=False
    )
    op.create_index(
        op.f("ix_leave_balances_employee_id"), "leave_balances", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_leave_balances_leave_type_id"), "leave_balances", ["leave_type_id"], unique=False
    )
    op.create_index(op.f("ix_leave_balances_year"), "leave_balances", ["year"], unique=False)
    op.add_column("leave_requests", sa.Column("layer1_notes", sa.Text(), nullable=True))
    op.add_column("leave_requests", sa.Column("layer2_notes", sa.Text(), nullable=True))
    op.add_column("leave_requests", sa.Column("rejected_by_user_id", sa.UUID(), nullable=True))
    op.add_column(
        "leave_requests", sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("leave_requests", sa.Column("rejection_reason", sa.Text(), nullable=True))
    op.add_column(
        "leave_requests", sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(op.f("ix_leave_requests_status"), "leave_requests", ["status"], unique=False)
    op.create_foreign_key(None, "leave_requests", "users", ["rejected_by_user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "leave_requests", type_="foreignkey")
    op.drop_index(op.f("ix_leave_requests_status"), table_name="leave_requests")
    op.drop_column("leave_requests", "cancelled_at")
    op.drop_column("leave_requests", "rejection_reason")
    op.drop_column("leave_requests", "rejected_at")
    op.drop_column("leave_requests", "rejected_by_user_id")
    op.drop_column("leave_requests", "layer2_notes")
    op.drop_column("leave_requests", "layer1_notes")
    op.drop_index(op.f("ix_leave_balances_year"), table_name="leave_balances")
    op.drop_index(op.f("ix_leave_balances_leave_type_id"), table_name="leave_balances")
    op.drop_index(op.f("ix_leave_balances_employee_id"), table_name="leave_balances")
    op.drop_index("ix_balance_employee_year", table_name="leave_balances")
    op.drop_table("leave_balances")
    # ### end Alembic commands ###
