"""extend_reimbursement_procurement_audit_fields

Revision ID: eab2758c6137
Revises: c4869330d466
Create Date: 2026-05-29 09:27:59.286542

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eab2758c6137"
down_revision: str | Sequence[str] | None = "c4869330d466"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("procurement_requests", sa.Column("request_date", sa.Date(), nullable=True))
    op.add_column(
        "procurement_requests", sa.Column("item_category", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "procurement_requests",
        sa.Column("actual_amount", sa.Numeric(precision=15, scale=2), nullable=True),
    )
    op.add_column(
        "procurement_requests", sa.Column("currency", sa.String(length=3), nullable=False)
    )
    op.add_column(
        "procurement_requests", sa.Column("expected_delivery_date", sa.Date(), nullable=True)
    )
    op.add_column(
        "procurement_requests", sa.Column("actual_delivery_date", sa.Date(), nullable=True)
    )
    op.add_column("procurement_requests", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column("procurement_requests", sa.Column("layer1_approver_id", sa.UUID(), nullable=True))
    op.add_column(
        "procurement_requests",
        sa.Column("layer1_approved_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("procurement_requests", sa.Column("layer1_notes", sa.Text(), nullable=True))
    op.add_column("procurement_requests", sa.Column("layer2_approver_id", sa.UUID(), nullable=True))
    op.add_column(
        "procurement_requests",
        sa.Column("layer2_approved_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("procurement_requests", sa.Column("layer2_notes", sa.Text(), nullable=True))
    op.add_column(
        "procurement_requests", sa.Column("rejected_by_user_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "procurement_requests", sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("procurement_requests", sa.Column("rejection_reason", sa.Text(), nullable=True))
    op.add_column(
        "procurement_requests", sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "procurement_requests", sa.Column("po_number", sa.String(length=50), nullable=True)
    )
    op.add_column("procurement_requests", sa.Column("ordered_at", sa.Date(), nullable=True))
    op.create_index(
        op.f("ix_procurement_requests_requested_by_user_id"),
        "procurement_requests",
        ["requested_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procurement_requests_status"), "procurement_requests", ["status"], unique=False
    )
    op.create_foreign_key(None, "procurement_requests", "users", ["layer1_approver_id"], ["id"])
    op.create_foreign_key(None, "procurement_requests", "users", ["layer2_approver_id"], ["id"])
    op.create_foreign_key(None, "procurement_requests", "users", ["rejected_by_user_id"], ["id"])
    op.add_column("reimbursements", sa.Column("category", sa.String(length=50), nullable=False))
    op.add_column("reimbursements", sa.Column("project_id", sa.UUID(), nullable=True))
    op.add_column("reimbursements", sa.Column("layer1_approver_id", sa.UUID(), nullable=True))
    op.add_column(
        "reimbursements", sa.Column("layer1_approved_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("reimbursements", sa.Column("layer1_notes", sa.Text(), nullable=True))
    op.add_column("reimbursements", sa.Column("layer2_approver_id", sa.UUID(), nullable=True))
    op.add_column(
        "reimbursements", sa.Column("layer2_approved_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("reimbursements", sa.Column("layer2_notes", sa.Text(), nullable=True))
    op.add_column("reimbursements", sa.Column("rejected_by_user_id", sa.UUID(), nullable=True))
    op.add_column(
        "reimbursements", sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("reimbursements", sa.Column("rejection_reason", sa.Text(), nullable=True))
    op.add_column(
        "reimbursements", sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("reimbursements", sa.Column("transferred_by_user_id", sa.UUID(), nullable=True))
    op.add_column(
        "reimbursements", sa.Column("transfer_reference", sa.String(length=100), nullable=True)
    )
    op.create_index(
        op.f("ix_reimbursements_category"), "reimbursements", ["category"], unique=False
    )
    op.create_index(op.f("ix_reimbursements_status"), "reimbursements", ["status"], unique=False)
    op.create_foreign_key(None, "reimbursements", "users", ["transferred_by_user_id"], ["id"])
    op.create_foreign_key(None, "reimbursements", "projects", ["project_id"], ["id"])
    op.create_foreign_key(None, "reimbursements", "users", ["layer1_approver_id"], ["id"])
    op.create_foreign_key(None, "reimbursements", "users", ["layer2_approver_id"], ["id"])
    op.create_foreign_key(None, "reimbursements", "users", ["rejected_by_user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reimbursements", type_="foreignkey")
    op.drop_constraint(None, "reimbursements", type_="foreignkey")
    op.drop_constraint(None, "reimbursements", type_="foreignkey")
    op.drop_constraint(None, "reimbursements", type_="foreignkey")
    op.drop_constraint(None, "reimbursements", type_="foreignkey")
    op.drop_index(op.f("ix_reimbursements_status"), table_name="reimbursements")
    op.drop_index(op.f("ix_reimbursements_category"), table_name="reimbursements")
    op.drop_column("reimbursements", "transfer_reference")
    op.drop_column("reimbursements", "transferred_by_user_id")
    op.drop_column("reimbursements", "cancelled_at")
    op.drop_column("reimbursements", "rejection_reason")
    op.drop_column("reimbursements", "rejected_at")
    op.drop_column("reimbursements", "rejected_by_user_id")
    op.drop_column("reimbursements", "layer2_notes")
    op.drop_column("reimbursements", "layer2_approved_at")
    op.drop_column("reimbursements", "layer2_approver_id")
    op.drop_column("reimbursements", "layer1_notes")
    op.drop_column("reimbursements", "layer1_approved_at")
    op.drop_column("reimbursements", "layer1_approver_id")
    op.drop_column("reimbursements", "project_id")
    op.drop_column("reimbursements", "category")
    op.drop_constraint(None, "procurement_requests", type_="foreignkey")
    op.drop_constraint(None, "procurement_requests", type_="foreignkey")
    op.drop_constraint(None, "procurement_requests", type_="foreignkey")
    op.drop_index(op.f("ix_procurement_requests_status"), table_name="procurement_requests")
    op.drop_index(
        op.f("ix_procurement_requests_requested_by_user_id"), table_name="procurement_requests"
    )
    op.drop_column("procurement_requests", "ordered_at")
    op.drop_column("procurement_requests", "po_number")
    op.drop_column("procurement_requests", "cancelled_at")
    op.drop_column("procurement_requests", "rejection_reason")
    op.drop_column("procurement_requests", "rejected_at")
    op.drop_column("procurement_requests", "rejected_by_user_id")
    op.drop_column("procurement_requests", "layer2_notes")
    op.drop_column("procurement_requests", "layer2_approved_at")
    op.drop_column("procurement_requests", "layer2_approver_id")
    op.drop_column("procurement_requests", "layer1_notes")
    op.drop_column("procurement_requests", "layer1_approved_at")
    op.drop_column("procurement_requests", "layer1_approver_id")
    op.drop_column("procurement_requests", "notes")
    op.drop_column("procurement_requests", "actual_delivery_date")
    op.drop_column("procurement_requests", "expected_delivery_date")
    op.drop_column("procurement_requests", "currency")
    op.drop_column("procurement_requests", "actual_amount")
    op.drop_column("procurement_requests", "item_category")
    op.drop_column("procurement_requests", "request_date")
    # ### end Alembic commands ###
